apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: transactions
  description: "Main provider for transactions API for retrieving tansaction data"
  title: Transactions
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: personal-finance-insights
  system: transactions
  providesApis:
    - transactions-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: transactions-api
  title: Transactions API
  description: "Retrieve transaction data for budgeting tools, expense management, and more."
spec:
  type: openapi
  lifecycle: production
  owner: personal-finance-insights
  system: liabilities
  definition: |
    openapi: 3.0.0
    info:
      title: Auth API
      description: API for retrieving bank account information for ACH transactions using Plaid.
      version: "1.0.0"
      contact:
        name: Payments Team
        email: payments-team@yourcompany.com
      license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html

    servers:
      - url: https://api.yourcompany.com
        description: Production server

    paths:
      /auth/get:
        x-plaid-business-unit-context: BUSINESS_UNIT_PLAID
        post:
          tags:
            - plaid
          summary: Retrieve auth data
          externalDocs:
            url: /api/products/auth/#authget
          operationId: authGet
          description: |-
            The `/auth/get` endpoint returns the bank account and bank identification numbers...
            # [Truncated for brevity, include your full description here]
          responses:
            "200":
              description: success
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/AuthGetResponse'
                  examples:
                    example-1:
                      value:
                        accounts:
                          - account_id: vzeNDwK7KQIm4yEog683uElbp9GRLEFXGK98D
                            balances:
                              available: 100
                              current: 110
                              limit: null
                              # [Truncated for brevity, include your full example here]
            default:
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/PlaidError'
              description: Default error
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AuthGetRequest'

    components:
      schemas:
        AuthGetResponse:
          type: object
          # Define the schema for AuthGetResponse
        AuthGetRequest:
          type: object
          # Define the schema for AuthGetRequest
        PlaidError:
          type: object
          # Define the schema for PlaidError
